name: fnx_rest
description: Angular and Flutter friendly RestClient, which will make your communication with REST APIs much simpler.
version: 4.0.0
authors:
  - Tomucha <tomucha@gmail.com>
  - Jiri Zuna <jiri@zunovi.cz>
  - Dafe Simonek <dafesimonek@gmail.com>
homepage: https://github.com/fnx-io/fnx_rest

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  logging: any
  http: '>=0.12.0 <1.0.0'
  pedantic: ^1.9.0

dev_dependencies:
  test: '^1.6.0'
  mockito: ^3.0.0
